Report warning when download rule failed in koolproxy initial script

diff --git a/files/etc/init.d/koolproxy b/files/etc/init.d/koolproxy
--- a/files/etc/init.d/koolproxy
+++ b/files/etc/init.d/koolproxy
@@ -13,6 +13,7 @@ USE_PROCD=1
 CONFIG=koolproxy
 PROG_PATH=/usr/share/koolproxy
 DATA_PATH=$PROG_PATH/data
+TEMP_PATH=/tmp
 
 config_n_get() {
 	local ret=$(uci get $CONFIG.$1.$2 2>/dev/null)
@@ -56,9 +57,15 @@ load_exrule() {
 		fi
 
 		if [ ! -f $DATA_PATH/$file ]; then
-			wget-ssl --quiet --timeout=5 --no-check-certificate $exrule -O $DATA_PATH/$file
-			uci set koolproxy.$1.time="`date +%Y-%m-%d" "%H:%M`"
-			uci commit koolproxy
+			wget-ssl --quiet --timeout=5 --no-check-certificate $exrule -O $TEMP_PATH/$file
+			if [ "$?" == "0" ]; then
+				uci set koolproxy.$1.time="`date +%Y-%m-%d" "%H:%M`"
+				uci commit koolproxy
+				mv $TEMP_PATH/$file $DATA_PATH/$file
+			else
+				echo "koolproxy download rule $file failed!"
+				[ -f $TEMP_PATH/$file ] && rm -f $TEMP_PATH/$file
+			fi
 		fi
 	fi
 }
